version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/xlsx"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/stat"
    schedule:
      interval: "daily"